### ISSUE TITLE
The status of App Log Ingestion is always Creating

### ISSUE THREAD

**Issue by chenhaiyun** [awslabs/log-hub#61] opened 2022-12-02 06:50 UTC
### Describe the bug

The status of App Log Ingestion is always Creating when I created an app log ingestion. 
![Xnip2022-12-02_14-40-43](https://user-images.githubusercontent.com/7011985/205231647-67f4dfc6-31ec-447c-921d-1aab3d633d87.jpg)

### Expected Behavior

The status of App Log Ingestion is Created after I create an app log ingestion. 

### Current Behavior

The status of App Log Ingestion is always Creating

### Reproduction Steps

1. Deploy Log Hub with version v1.1.1.
2. Create a Log Config in v1.1.1
3. Upgrade Log Hub to version v1.2.0
4. Edit the Log Config when we created in v1.1.1 and Save
5. Create an App Pipeline
6. Create an App Log Ingestion with EC2 and the Config we just Edited
7.  In the App Pipeline page and watch the status of the ingestion we created. 

### Possible Solution

Create a new Log Config in Log Hub v1.2.0 and use the new Log Config to create an app log ingestion.

### Log Hub Version

v1.2.0

### AWS Region. e.g., us-east-1

all-region

**Comment by JoeShi** [comment] 2022-12-04 13:36
The issue has been fixed in v1.2.1

**Closed by JoeShi** 2022-12-04 13:36 UTC
Labels: bug

**Comment by JoeShi** [comment] 2022-12-05 03:54
The root cause is because the Log Config created in v1.1.X is not compatible with v1.2.x. We have fixed this issue.
